runtime: python27
api_version: 1
threadsafe: true
handlers:
# Handle the main page by serving the index page.
# Note the $ to specify the end of the path, since app.yaml does prefix matching.
- url: /$
  static_files: static/index.html
  upload: static/index.html


# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: static/\1/index.html
  upload: static/.*/index.html

# Handle nearly every other file by just serving it.
- url: /(.+)
  static_files: static/\1
  upload: static/(.*)


# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*

